"""added scheduling to jobs table

Revision ID: ba1da4fa3584
Revises: aca1a69afcb1
Create Date: 2026-03-31 17:11:39.581761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1da4fa3584'
down_revision: Union[str, Sequence[str], None] = 'aca1a69afcb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('jobs', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'end_time')
    op.drop_column('jobs', 'start_time')
    # ### end Alembic commands ###
